server:
  port: 9006
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1MB
spring:
  application:
    name: traceapi
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_LOWER=TRUE;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    #data: classpath:data-h2.sql
  h2:
    console:
      enabled: true
      path: /h2

logging:
  level:
    org.springframework.jdbc.core: DEBUG

trace:
  delay: 60
  unit: SECONDS