server:
  port: 9006
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1MB
spring:
  application:
    name: inspect
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_LOWER=TRUE;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    #data: classpath:data-h2.sql
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
  h2:
    console:
      enabled: true
      path: /h2

logging:
  level:
    org.usf.jquery: DEBUG
    org.usf.inspect: TRACE
    org.springframework.jdbc.core: DEBUG

inspect:
  enabled: true
  dispatch:
    delay: 5
    unit: SECONDS
    buffer-max-size: -1 #inspect-server only
# target: REMOTE => log only
# track:
#   jdbc-request: false
#   rest-request: false
#   main-session: false
#   rest-session: false
# server:
#   host:
#   compress-min-size: