server:
  port: 9006
spring:
  application:
    name: traceapi
  datasource:
    url: jdbc:h2:mem:testdb;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2

trace:
  period: 1
  time-unit: MINUTES

logging:
  level:
    org.springframework.jdbc.core: DEBUG