server:
  port: 9006
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1MB
spring:
  application:
    name: traceapi
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_LOWER=TRUE;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    #data: classpath:data-h2.sql
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  h2:
    console:
      enabled: true
      path: /h2

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.usf.traceapi: TRACE
    org.usf.jquery: DEBUG

inspect:
  enabled: true
  mode: #REMOTE => log only
  dispatch:
    delay: 60
    unit: SECONDS
#  track:
#    jdbc-request: true
#    rest-request: true
#    main-session: true
#    rest-session: true
#   buffer-max-size: -1
# server:
#   host:
#   compress-min-size: